# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete"
kotlin.code.style=official
# Non-transitive R classes
android.nonTransitiveRClass=true
# R8 全模式，进一步压缩体积
android.enableR8.fullMode=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
