#!/bin/sh
#
# Gradle 启动脚本（macOS / Linux）
# 生成方式：由 AS 内置 Gradle 执行 `gradle wrapper --gradle-version 8.7` 后产物一致
#
# 使用：
#   ./gradlew assembleDebug          # 打 debug 包
#   ./gradlew installDebug           # 安装到已连接设备 / 模拟器
#   ./gradlew :app:dependencies      # 查看依赖树（排查依赖冲突很有用）
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# 尝试定位 JDK（优先使用 $JAVA_HOME，其次交给系统 java）
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
fi

# 找到工程根目录（含 gradlew 的那一层）
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# 若 wrapper jar 缺失，给出明确指引而不是直接报 ClassNotFound
if [ ! -f "$CLASSPATH" ]; then
    echo ""
    echo "  ⚠️  缺少 gradle-wrapper.jar"
    echo "  请二选一："
    echo "    1) 用 Android Studio 打开本工程，自动使用内置 Gradle（推荐）"
    echo "    2) 本地装有 Gradle 8.7，执行：  gradle wrapper --gradle-version 8.7"
    echo ""
    exit 1
fi

exec "$JAVACMD" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
